# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_creater',
            field=models.IntegerField(max_length=255),
        ),
    ]
